#!/usr/bin/env python3
"""Generate the fallback-display property from a verified Unicode data file."""
import hashlib
import pathlib
import sys

VERSION = '16.0.0'
SHA256 = '39d35161f2954497f69e08bdb9e701493f476a3d30222de20028feda36c1dabd'
data = pathlib.Path(sys.argv[1]).read_bytes()
if hashlib.sha256(data).hexdigest() != SHA256:
    raise SystemExit('Expected pinned Unicode 16.0.0 DerivedCoreProperties.txt')
ranges = []
for line in data.decode('utf-8').splitlines():
    fields = line.split('#')[0].strip().split(';')
    if len(fields) != 2 or fields[1].strip() != 'Default_Ignorable_Code_Point':
        continue
    bounds = fields[0].strip().split('..')
    lo, hi = int(bounds[0], 16), int(bounds[-1], 16)
    if ranges and lo == ranges[-1][1] + 1:
        ranges[-1] = (ranges[-1][0], hi)
    else:
        ranges.append((lo, hi))
print('// Generated by tools/unicode/generate-default-ignorables.py; Unicode ' + VERSION)
print('// Source: https://www.unicode.org/Public/' + VERSION + '/ucd/DerivedCoreProperties.txt')
print('// SHA-256: ' + SHA256)
print('// Unicode data license: third_party/unicode.LICENSE')
print('#pragma once\n#include <array>\n#include <cstdint>\n\nnamespace pmjs {')
print('inline bool isDefaultIgnorable(std::uint32_t codepoint) {')
print('  static constexpr std::array ranges{')
for lo, hi in ranges:
    print(f'    std::array<std::uint32_t, 2>{{0x{lo:X}, 0x{hi:X}}},')
print('  };\n  for (const auto& range : ranges) {\n    if (codepoint < range[0]) return false;\n    if (codepoint <= range[1]) return true;\n  }\n  return false;\n}\n}  // namespace pmjs')
