include("${CMAKE_CURRENT_LIST_DIR}/portable-arm64.cmake")
foreach(search_variable IN ITEMS CPATH C_INCLUDE_PATH CPLUS_INCLUDE_PATH LIBRARY_PATH CFLAGS CXXFLAGS LDFLAGS)
  if(NOT "$ENV{${search_variable}}" STREQUAL "")
    message(FATAL_ERROR "Unset ${search_variable}; target include/library searches must come from the reviewed SDK")
  endif()
endforeach()
set(PMJS_LINUX_ARM64_BUILD ON CACHE BOOL "Use the reviewed ARM64/glibc 2.28 environment" FORCE)
set(CMAKE_C_FLAGS_INIT "-DMESA_EGL_NO_X11_HEADERS")
set(CMAKE_CXX_FLAGS_INIT "-DMESA_EGL_NO_X11_HEADERS")
set(PMJS_DEPENDENCY_PREFIX "${PMJS_SDK_ROOT}/prefix" CACHE PATH "Target dependencies" FORCE)
set(PMJS_DEPENDENCY_LOCK "${PMJS_SDK_ROOT}/dependencies.cmake" CACHE FILEPATH "Target dependency versions" FORCE)
set(PMJS_NODE_ROOT "$ENV{PMJS_NODE_ROOT}" CACHE PATH "Selected target Node SDK")
if(NOT EXISTS "${PMJS_NODE_ROOT}/include/node/node_api.h")
  message(FATAL_ERROR "PMJS_NODE_ROOT must name the prepared ARM64 Node SDK")
endif()
set(PMJS_NODE_API_HEADERS "${PMJS_NODE_ROOT}/include/node" CACHE PATH "Selected Node-API headers" FORCE)
set(ENV{PKG_CONFIG_PATH} "")
set(ENV{PKG_CONFIG_LIBDIR} "${PMJS_SDK_ROOT}/prefix/lib/pkgconfig")
set(ENV{PKG_CONFIG_SYSROOT_DIR} "")
set(PKG_CONFIG_USE_CMAKE_PREFIX_PATH OFF CACHE BOOL "Exclude host search paths" FORCE)
set(CMAKE_TRY_COMPILE_PLATFORM_VARIABLES PMJS_NODE_ROOT)
