// Generated by tools/unicode/generate-default-ignorables.py; Unicode 16.0.0
// Source: https://www.unicode.org/Public/16.0.0/ucd/DerivedCoreProperties.txt
// SHA-256: 39d35161f2954497f69e08bdb9e701493f476a3d30222de20028feda36c1dabd
// Unicode data license: third_party/unicode.LICENSE
#pragma once
#include <array>
#include <cstdint>

namespace pmjs {
inline bool isDefaultIgnorable(std::uint32_t codepoint) {
  static constexpr std::array ranges{
    std::array<std::uint32_t, 2>{0xAD, 0xAD},
    std::array<std::uint32_t, 2>{0x34F, 0x34F},
    std::array<std::uint32_t, 2>{0x61C, 0x61C},
    std::array<std::uint32_t, 2>{0x115F, 0x1160},
    std::array<std::uint32_t, 2>{0x17B4, 0x17B5},
    std::array<std::uint32_t, 2>{0x180B, 0x180F},
    std::array<std::uint32_t, 2>{0x200B, 0x200F},
    std::array<std::uint32_t, 2>{0x202A, 0x202E},
    std::array<std::uint32_t, 2>{0x2060, 0x206F},
    std::array<std::uint32_t, 2>{0x3164, 0x3164},
    std::array<std::uint32_t, 2>{0xFE00, 0xFE0F},
    std::array<std::uint32_t, 2>{0xFEFF, 0xFEFF},
    std::array<std::uint32_t, 2>{0xFFA0, 0xFFA0},
    std::array<std::uint32_t, 2>{0xFFF0, 0xFFF8},
    std::array<std::uint32_t, 2>{0x1BCA0, 0x1BCA3},
    std::array<std::uint32_t, 2>{0x1D173, 0x1D17A},
    std::array<std::uint32_t, 2>{0xE0000, 0xE0FFF},
  };
  for (const auto& range : ranges) {
    if (codepoint < range[0]) return false;
    if (codepoint <= range[1]) return true;
  }
  return false;
}
}  // namespace pmjs
