if(POLICY CMP0135)
  cmake_policy(SET CMP0135 NEW)
endif()

include(FetchContent)
find_package(Git REQUIRED)
set(effekseer_revision "e0ccaf1d1837b1d178d0088f714a1f4525cae8f4")
set(effekseer_archive_sha "e2cb5aefdf1bf84d0d050fd44fcc64aa35baeee957686768a508784f1ed243d1")
set(effekseer_patch "${CMAKE_CURRENT_SOURCE_DIR}/third_party/effekseer-mz.patch")
file(SHA256 "${effekseer_patch}" patch_sha)
string(SHA256 source_key "${effekseer_archive_sha}:${patch_sha}")
set_property(DIRECTORY APPEND PROPERTY CMAKE_CONFIGURE_DEPENDS "${effekseer_patch}")

if(FETCHCONTENT_SOURCE_DIR_PMJS_EFFEKSEER)
  execute_process(COMMAND "${GIT_EXECUTABLE}" apply --reverse --check "${effekseer_patch}"
    WORKING_DIRECTORY "${FETCHCONTENT_SOURCE_DIR_PMJS_EFFEKSEER}"
    RESULT_VARIABLE patch_status ERROR_VARIABLE patch_error)
  if(NOT patch_status EQUAL 0)
    message(FATAL_ERROR "Custom Effekseer source must already contain the pinned patch: ${patch_error}")
  endif()
endif()

FetchContent_Declare(pmjs_effekseer
  URL "https://codeload.github.com/effekseer/Effekseer/tar.gz/${effekseer_revision}"
  URL_HASH "SHA256=${effekseer_archive_sha}"
  SOURCE_DIR "${FETCHCONTENT_BASE_DIR}/pmjs_effekseer-${source_key}-src"
  PATCH_COMMAND "${GIT_EXECUTABLE}" apply "${effekseer_patch}")

function(pmjs_build_effekseer)
  set(BUILD_VIEWER OFF)
  set(BUILD_EDITOR OFF)
  set(BUILD_TEST OFF)
  set(BUILD_EXAMPLES OFF)
  set(BUILD_UNITYPLUGIN OFF)
  set(BUILD_UNITYPLUGIN_FOR_IOS OFF)
  set(BUILD_GL ON)
  set(BUILD_DX9 OFF)
  set(BUILD_DX11 OFF)
  set(BUILD_DX12 OFF)
  set(BUILD_METAL OFF)
  set(BUILD_VULKAN OFF)
  set(BUILD_WITH_EASY_PROFILER OFF)
  set(NETWORK_ENABLED OFF)
  set(USE_LIBPNG_LOADER OFF)
  set(USE_OPENAL OFF)
  set(USE_OPENGLES2 ON)
  set(USE_OPENGLES3 OFF)
  if(DEFINED CACHE{CMAKE_WARN_DEPRECATED})
    set(pmjs_had_warn_deprecated TRUE)
    set(pmjs_prev_warn_deprecated "$CACHE{CMAKE_WARN_DEPRECATED}")
  else()
    set(pmjs_had_warn_deprecated FALSE)
  endif()
  set(CMAKE_WARN_DEPRECATED OFF CACHE BOOL "" FORCE)
  FetchContent_MakeAvailable(pmjs_effekseer)
  if(pmjs_had_warn_deprecated)
    set(CMAKE_WARN_DEPRECATED "${pmjs_prev_warn_deprecated}" CACHE BOOL "" FORCE)
  else()
    unset(CMAKE_WARN_DEPRECATED CACHE)
  endif()
  target_include_directories(Effekseer SYSTEM PUBLIC "$<BUILD_INTERFACE:${pmjs_effekseer_SOURCE_DIR}/Dev/Cpp/Effekseer>")
  target_include_directories(EffekseerRendererGL SYSTEM PUBLIC "$<BUILD_INTERFACE:${pmjs_effekseer_SOURCE_DIR}/Dev/Cpp/EffekseerRendererGL>")
  target_link_libraries(EffekseerRendererGL PUBLIC PkgConfig::GLES PkgConfig::EGL)
  # Upstream's Linux ES2 backend omits EGL and the shared ES3 token declarations.
  target_compile_options(EffekseerRendererGL PRIVATE "SHELL:-include EGL/egl.h" "SHELL:-include GLES3/gl3.h")
  # Upstream defines these ES backend tokens only for Windows/Android/Apple.
  target_compile_definitions(EffekseerRendererGL PRIVATE GL_BGRA=0x80E1 GL_DEPTH_COMPONENT32=0x81A7)
endfunction()

pmjs_build_effekseer()
